# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Koirala Suppliers
  # ---------------------------------------------------------------------------
  - Name: Koirala
    Domain: koirala.bfp.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1