version: '2'

volumes:
  ca.shrestha.bfp.com:
  couchdb.shrestha.peer0:
  peer0.shrestha.bfp.com:

networks:
  bfp:

services:
  ca.shrestha.bfp.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.shrestha.bfp.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.shrestha.bfp.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.shrestha.bfp.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-shrestha/peerOrganizations/shrestha.bfp.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.shrestha.bfp.com
    networks:
      - bfp

  couchdb.shrestha.peer0:
    container_name: couchdb.shrestha.peer0
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - 7984:5984
    networks:
      - bfp

  peer0.shrestha.bfp.com:
    container_name: peer0.shrestha.bfp.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_bfp
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.shrestha.peer0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_ID=peer0.shrestha.bfp.com
      - CORE_PEER_ADDRESS=peer0.shrestha.bfp.com:7051
      - CORE_PEER_LOCALMSPID=ShresthaMSP
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.shrestha.bfp.com:7051
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./crypto-shrestha/peerOrganizations/shrestha.bfp.com/peers/peer0.shrestha.bfp.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-shrestha/peerOrganizations/shrestha.bfp.com/peers/peer0.shrestha.bfp.com/tls:/etc/hyperledger/fabric/tls
      - peer0.shrestha.bfp.com:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    networks:
      - bfp
    depends_on:
      - couchdb.shrestha.peer0
    ports:
      - 9051:7051
      - 9053:7053

  shrestha-cli:
    container_name: shrestha-cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=shrestha-cli
      - CORE_PEER_ADDRESS=peer0.shrestha.bfp.com:7051
      - CORE_PEER_LOCALMSPID=ShresthaMSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/shrestha.bfp.com/users/Admin@shrestha.bfp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../../BFP-Chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-shrestha:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ../OrdererOrg/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.shrestha.bfp.com
    networks:
      - bfp